version: '2'
services:
    db:
        image: mariadb:5.5.50
        environment:
            MYSQL_ROOT_PASSWORD: 123qwe
            MYSQL_DATABASE: the_db
            MYSQL_USER: the_user
            MYSQL_PASSWORD: 123qwe
        ports:
            - "13306:3306"
        volumes:
            - data:/var/lib/mysql
    ssh:
        build: ./openssh
        ports:
            - "10022:22"
        volumes:
            - files:/code
            - ssh:/home
    php:
        build: ./php
        volumes:
            - files:/code
    web:
        build: ./nginx
        ports:
            - "10080:80"
            - "10443:443"
        volumes:
            - files:/code
volumes:
    data: {  }
    files: {  }
    ssh: {  }
